version: '3.8'

services:
  ingest-service:
    build: ./ingest_service
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/app/chroma_db
    depends_on:
      - chroma

  query-service:
    build: ./query_service
    ports:
      - "8001:8001"
    volumes:
      - chroma_data:/app/chroma_db
    depends_on:
      - chroma
      - ollama

  chroma:
    image: chromadb/chroma:0.6.3
    ports:
      - "8002:8000"
    volumes:
      - chroma_data:/chroma/chroma_db

  ollama:
    build: ./ollama_service
    ports:
      - "11434:11434"

volumes:
  chroma_data: